builds:
  - binary: kpicker
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags: -d -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
archive:
  format: binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

# $WERCKER_OUTPUT_DIR: /pipeline/output/
dist: /pipeline/output/