box:
  id: golang

build:
  steps:
    - wercker/setup-go-workspace:
        package-dir: github.com/fenrirunbound/kubeconfig-picker
    - script:
        name: install go tools
        code: |
          go version
          go get -u -v github.com/golang/dep
          go get -u -v github.com/golang/dep/cmd/dep
    - wercker/golint
    - wercker/dep
    - script:
        name: go test
        code: |
          go test ./...
    - script:
        name: go build
        code: |
          go build ./...
    