box:
  id: golang

build:
  steps:
    - wercker/setup-go-workspace:
        package-dir: github.com/fenrirunbound/kubeconfig-picker
    - wercker/golint
    - wercker/dep
    - script:
        name: go test
        code: |
          go test ./...
    - script:
        name: go build
        code: |
          go build ./...

deploy:
  steps:
    - wercker/setup-go-workspace:
        package-dir: github.com/fenrirunbound/kubeconfig-picker
    - wercker/dep
    - script:
        name: goreleaser
        code: |
          curl -sL https://git.io/goreleaser | bash
    