apiVersion: v1
clusters:
- cluster:
    certificate-authority: ZHVtbXlEYXRh
    server: https://somewhere.com
  name: randomCluster
- cluster:
    certificate-authority: ZHVtbXlEYXRh
    server: https://somewhere.com
  name: myClusterName
- cluster:
    certificate-authority: ZHVtbXlEYXRh
    server: https://somewhere.com
  name: otherCluster
contexts:
- context:
    cluster: otherCluster
    namespace: namespace
    user: someUser
  name: otherContextName
- context:
    cluster: myClusterName
    namespace: namespace
    user: someUser
  name: myContextName
- context:
    cluster: randomCluster
    namespace: namespace
    user: someUser
  name: lastContextName
current-context: myContextName
kind: Config
preferences: {}
users:
- name: someUser
  user:
    client-certificate-data: ZHVtbXlEYXRh
    client-key-data: ZHVtbXlEYXRh

