apiVersion: v1
clusters:
- cluster:
    certificate-authority: ZHVtbXlEYXRh
    server: https://somewhere.com
  name: randomCluster
contexts:
- context:
    cluster: randomCluster
    namespace: namespace
    user: someUser
  name: lastContextName
current-context: ""
kind: Config
preferences: {}
users:
- name: someUser
  user:
    client-certificate-data: ZHVtbXlEYXRh
    client-key-data: ZHVtbXlEYXRh
